apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"initContainers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"fix-permissions"}],"containers":[{"limits":{"cpu":"200m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"},"name":"cloud-sql-proxy"},{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"1Gi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"mlflow"}]},"output":{"initContainers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"fix-permissions"}],"containers":[{"limits":{"cpu":"200m","ephemeral-storage":"1Gi","memory":"512Mi"},"requests":{"cpu":"100m","ephemeral-storage":"1Gi","memory":"256Mi"},"name":"cloud-sql-proxy"},{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"1Gi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"mlflow"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.19-gke.1
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mlflow"},"name":"mlflow","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mlflow"}},"template":{"metadata":{"labels":{"app":"mlflow"}},"spec":{"containers":[{"env":[{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"db-password","name":"mlflow-db-secret"}}},{"name":"DB_HOST","valueFrom":{"secretKeyRef":{"key":"db-host","name":"mlflow-db-secret"}}},{"name":"DB_PORT","value":"5432"},{"name":"DB_NAME","valueFrom":{"secretKeyRef":{"key":"db-name","name":"mlflow-db-secret"}}},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"db-user","name":"mlflow-db-secret"}}},{"name":"MLFLOW_ARTIFACTS_DESTINATION","value":"/mlflow/artifacts"}],"image":"us-central1-docker.pkg.dev/gen-lang-client-0282248851/ai-platform/mlflow:latest","name":"mlflow","ports":[{"containerPort":5000,"name":"http"}],"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/mlflow","name":"mlflow-data"}]}],"initContainers":[{"args":["mkdir -p /mlflow/artifacts\nchmod -R 777 /mlflow\necho \"Permissions fixed\"\n"],"command":["sh","-c"],"image":"busybox:1.36","name":"fix-permissions","volumeMounts":[{"mountPath":"/mlflow","name":"mlflow-data"}]}],"volumes":[{"name":"mlflow-data","persistentVolumeClaim":{"claimName":"mlflow-pvc"}}]}}}}
  creationTimestamp: "2025-10-19T14:18:44Z"
  generation: 11
  labels:
    app: mlflow
  name: mlflow
  namespace: default
  resourceVersion: "1761229152958687003"
  uid: 631ee7f2-29a9-4850-9742-8c2ecddf4b1c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mlflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-23T10:19:07-04:00"
      creationTimestamp: null
      labels:
        app: mlflow
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: mlflow-db-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db-host
              name: mlflow-db-secret
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db-name
              name: mlflow-db-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db-user
              name: mlflow-db-secret
        - name: MLFLOW_ARTIFACTS_DESTINATION
          value: /mlflow/artifacts
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: /mlflow/artifacts
        - name: MLFLOW_BACKEND_STORE_URI
          value: postgresql://mlflow:mlflow@10.116.0.5/mlflow
        image: us-central1-docker.pkg.dev/gen-lang-client-0282248851/ai-platform/mlflow:latest
        imagePullPolicy: Always
        name: mlflow
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mlflow
          name: mlflow-data
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          mkdir -p /mlflow/artifacts
          chmod -R 777 /mlflow
          echo "Permissions fixed"
        command:
        - sh
        - -c
        env:
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: /mlflow/artifacts
        - name: MLFLOW_BACKEND_STORE_URI
          value: postgresql://mlflow:mlflow@10.116.0.5/mlflow
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        name: fix-permissions
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mlflow
          name: mlflow-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-22T06:36:35Z"
    lastUpdateTime: "2025-10-22T06:36:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-19T14:18:44Z"
    lastUpdateTime: "2025-10-23T14:19:12Z"
    message: ReplicaSet "mlflow-fc8479f99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
